### ISSUE TITLE
The peer authenticated to public key which did not match the dialed peer's public key 

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#5903] opened 2023-11-03 13:30 UTC
**Describe the bug**
This is a wallet and the two nodes mentioned below are its peer base nodes, both of which were running
```
2023-11-03 13:50:29.713721100 [wallet::connectivity] WARN  Connectivity error: ConnectionFailed: The peer authenticated to public key '3e1186f43d8ef1251fa11816fed69a494ce1392a61f5d7c645bf04a5d0459358' which did not match the dialed peer's public key '3c7765c144f743dc167470291e08557a88519bebd88b418fed4f6690bc142046'
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS & Version: [e.g. iOS 10.2.1]
 - Browser & Version [e.g. chrome v71.0.12345]

**Smartphone (please complete the following information):**
 - Browser & Version [e.g. stock browser v0.1.2]

**Additional context**

**Comment by SWvheerden** [comment] 2023-11-08 12:39
duplicate of #5792

**Closed as completed by SWvheerden** 2023-11-08 12:39 UTC
