### ISSUE TITLE
OutputManagerBackend methods for OutputManagerSqliteDatabase need transactions

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari#1573] opened 2020-03-23 17:08 UTC
Methods such as `confirm_transaction` that perform multiple SQL statements in OutputManagerSqliteDatabase need transactions to prevent mangling of data. 

e.g. change to:
```
 fn confirm_transaction(&self, tx_id: u64) -> Result<(), OutputManagerStorageError> {
        let conn = acquire_lock!(self.database_connection);

        conn.transaction(move || {
            match PendingTransactionOutputSql::find(tx_id, &(*conn)) {
                Ok(p) => {
                    let outputs = OutputSql::find_by_tx_id_and_encumbered(tx_id, &(*conn))?;
...
         })?;


        Ok(())
    }

```
 If this is not done and there is a failure of some kind, some of the outputs might be marked as Spent/Unspent and others not.

**Comment by philipr-za** [comment] 2020-03-27 11:40
Duplicate of https://github.com/tari-project/tari/issues/908

But leaving as it has a better description.

**Closed** 2022-11-15 14:25 UTC
Labels: C-bug
