### ISSUE TITLE
WIP - [UI Enhancement] Emoji ID chunking

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1177] opened 2020-01-10 15:52 UTC
In order to be able to more easily quickly scan and visually verify Emoji IDs, we are implementing chunking so that each group of 3-4 emojis is now delimited with a pipe.   We need to go through the existing screens we've built and add the chunking.

**Open Question:** @CjS77 Do we know how many emojis we're going to have? We should probably wait to implement this until we know for sure

**Design Specs:** https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5e189d56a44512ac53b516e7

**Acceptance Criteria** 

- Wherever an Emoji ID appears, it appears with chunking as follows: (INSERT ZEPLIN IMAGE AFTER # OF EMOJIS DETERMINED)

**Comment by CjS77** [comment] 2020-01-14 17:32
@fluffypony is still finalising the spec. IIRC it's 13 or so

**Comment by CjS77** [comment] 2020-01-14 17:34
Are there places where an emoji ID will be displayed and pipes will not be used?

**Comment by talmahaj** [comment] 2020-01-14 23:38
Not that I can think of, since we’d want to be consistent with how we display it.

**Comment by Jasonvdb** [comment] 2020-02-06 10:10
@Karim-tari @talmahaj  emojis are chunked in one part and clipped in other parts. Are these always going to be 2 separate components? Is the second one a button or are they both buttons? If they are, what's the expected behaviour when tapped?
 
<img width="316" alt="Screenshot 2020-02-06 at 12 03 27" src="https://user-images.githubusercontent.com/5300488/73927069-65213680-48d9-11ea-8b59-93edd5ea8bec.png">


![Screenshot 2020-02-06 at 12 05 11](https://user-images.githubusercontent.com/5300488/73927065-63577300-48d9-11ea-9878-256f81087b5c.png)

I want to create an iOS issue to create a more unified reusable component for this but need more spec details.

**Comment by CjS77** [comment] 2020-02-07 04:23
Also, since the ids are 25 chars long, we should chunk em on groups of 5.
h/t @kukabi for the suggestion.

**Comment by Tas4tari** [comment] 2020-06-09 12:57
@CjS77 @kukabi @Jasonvdb @talmahaj eMoji's are chunked in a group of three and in both IOS and Android on the following screens:
Onboarding, Add amount, add note, Transaction Details screen. Closing this issue off

**Closed by Tas4tari** 2020-06-09 12:57 UTC
