### ISSUE TITLE
Transaction request body too large for RPC message

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#5880] opened 2023-10-27 10:16 UTC
**Describe the bug**
A large transaction was negotiated between two wallets, but could not be broadcast to a base node.

```
Transaction Details────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│TxID:                   464757864993859053                                                                                         │
│Source Address:         🚀🐮🚀👛👻🐾📡🏉🍭🎷🎼📷💔📝🐲🐽🐷🍉🐗🏭👚🐮🍇🔥🎹🍁💦🚲🐻👚🚧🍔🐘                                         │
│Destination address:    🐎🎸🐰🐳🍬🍟🎧🌞🎱🍦💌🍕📚🔫🔩🐊💤🍈👠💼👻🐜🔭🍪🎢🐜🏁💍🍎🔎🎂🎸🐞                                         │
│Direction:              Inbound                                                                                                    │
│Amount:                 30000000.000000 T                                                                                          │
│Fee:                    44516 µT (weight: 44516g, #inputs: 5549, #outputs: 2)                                                      │
│Status:                 Completed                                                                                                  │
│Message:                                                                                                                           │
│Mined At (Local):                                                                                                                  │
│Imported At (Local):    2023-10-25 14:43:13                                                                                        │
│Excess:                 8683dcc56545e4abb32ceaf1e2507af604b5c1694e482d0a1101df307c4f1500                                           │
│Confirmations:          N/A                                                                                                        │
│Mined Height:           N/A                                                                                                        │
│Maturity:               N/A                                                                                                        │
```

```
2023-10-27 09:53:01.220824600 [wallet::transaction_service::protocols::broadcast_protocol] INFO  Submitting Transaction (TxId: 464757864993859053) with signature '8683dcc56545e4abb32ceaf1e2507af604b5c1694e482d0a1101df307c4f1500' to Base Node
2023-10-27 09:53:01.254314900 [wallet::transaction_service::protocols::broadcast_protocol] INFO  Submit Transaction RPC Call to Base Node failed: Request failed: General: Request body was too large. Expected <= 3145728 but got 3287111
```

**Expected behavior**

Transactions that can be negotiated between wallets should be accepted by base nodes.

**Comment by SWvheerden** [comment] 2024-01-30 07:29
Duplicate of #6108

**Closed as completed by SWvheerden** 2024-01-30 07:29 UTC
Labels: P-high-risk
