### ISSUE TITLE
[CI] Investigate CI test failure

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#5268] opened 2023-03-24 14:37 UTC
Test failed on CI, but succeeded locally. 
```
running 4 tests
test pruned\_mmr\_empty ... ok
test calculate\_mmr\_roots ... ok
test calculate\_pruned\_mmr\_roots ... FAILED
)test pruned\_mmrs ... ok



failures:



\---- calculate\_pruned\_mmr\_roots stdout ----

thread 'calculate\_pruned\_mmr\_roots' panicked at 'assertion failed: \`(left == right)\`

 left: \`\[115, 144, 67, 185, 145, 204, 211, 15, 120, 144, 121, 221, 175, 142, 107, 36, 74, 19, 201, 139, 110, 18, 8, 196, 15, 81, 200, 31, 111, 171, 16, 224\]\`,

right: \`\[38, 169, 21, 216, 240, 207, 113, 15, 40, 126, 254, 144, 70, 84, 246, 242, 162, 255, 254, 8, 152, 108, 63, 27, 186, 27, 67, 76, 55, 173, 113, 200\]\`', base\_layer/mmr/tests/pruned\_mmr.rs:104:5

note: run with \`RUST\_BACKTRACE=1\` environment variable to display a backtrace
```

**Comment by AaronFeickert** [comment] 2023-03-27 13:44
I was able to trigger local test failures by running the test on a loop. It's not a deterministic failure, so it must occur only on certain randomized parameters.

**Comment by AaronFeickert** [comment] 2023-03-27 14:37
The cause appears to be specific to the deletion functionality of the underlying mutable MMR implementation. If you use an empty deletion index vector in the test, it will always succeed.

**Comment by AaronFeickert** [comment] 2023-03-28 15:09
Looks like this is in fact a test failure. [The test in question](https://github.com/tari-project/tari/blob/e334a404e432b0911bae3054a28d8e8ca5876e6c/base_layer/mmr/tests/pruned_mmr.rs#L86-L105) fails to compress the deletion bitmap before computing a Merkle root.

Depending on implementation details, it may be useful to move the compression directly into the `get_merkle_root` functionality if feasible, to avoid the case where a caller forgets to compress and results in a possibly different root.

**Comment by AaronFeickert** [comment] 2023-03-28 17:53
Addressed by [PR 5278](https://github.com/tari-project/tari/pull/5278).

**Closed as completed** 2023-03-28 18:20 UTC
Labels: C-bug, A-base_node
