### ISSUE TITLE
predictable hash function

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#152] opened 2019-03-11 13:10 UTC
We need to create a hash function with predictable results for the fuzz testing

child of #151

**Comment by SWvheerden** [comment] 2019-03-18 08:28
technically yes, 

But I want to know what the hash is going to be before I calculate it, the reason being for example:
Hash(Hash(1)||Hash(2)) = Some random chars, that you have to calculate before hand. Thats fine for small MMR's but if you have 100 000 leaves, then it becomes a bit difficult. 

I was thinking along the lines of if you hash 1, it gives you 1, 2 -> 2 etc, Concatenate gives you 12.
Something along those lines, that makes it easy to quickly know what the answer of a long line of connected hashes are without calculating each hash before hand

**Comment by CjS77** [comment] 2020-01-19 14:06
Dupe of #387 ?

**Comment by SWvheerden** [comment] 2020-01-20 05:29
Differant issues. 
387 is to make sure we use LE order of bytes. 
152 is having a predictable hash function, which means its broken in the sense of a hash function, but will be great for testing

**Closed** 2021-03-02 08:18 UTC
Labels: duplicate
