### ISSUE TITLE
[console wallet] Transaction details wording does not reflect Tari address but public key

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#5017] opened 2022-12-07 15:01 UTC
On:
- Transactions Details pane
- Completed Transactions pane
- Pending Transactions pane

**Comment by SWvheerden** [comment] 2022-12-08 08:21
https://github.com/tari-project/tari/issues/4939
The tx tab needs some love

**Comment by SWvheerden** [comment] 2023-01-05 06:53
closing this as is duplicate of issue #4939

**Closed as completed by SWvheerden** 2023-01-05 06:53 UTC
