### ISSUE TITLE
Implement struct/trait for Mining worker

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#70] opened 2019-01-18 12:20 UTC
child of #33

**Comment by CjS77** [comment] 2019-02-20 08:14
Duplicate of #71?

**Comment by neonknight64** [comment] 2019-02-27 08:38
As Monero will hard fork the PoW algorithm every 6 month we should make use of current stratum miners as Mining Workers. No need to implement this.

**Closed** 2019-11-07 06:24 UTC
